--
-- PostgreSQL database dump
--

\restrict Nzlvjhq4pSIbcsUwQLU7uhyUMjMOzYxHjmacU1nqPx9CN83RxjH8iFskeh0lsZv

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: workspaces; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('e61966ed-18c2-425c-8e83-f466dd5902bb', 'Alekh Jindal', 'alekh8nfh', 'f2bd2f15-7a77-447a-9ac2-f61a7135f5d2', NULL, '{"company_name": "Alekh''s Workspace", "default_timezone": "America/Los_Angeles"}', '2025-12-15 15:12:10.625316+00', '2025-12-15 15:12:10.625316+00', NULL, NULL, 'alekh', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'trial', NULL, NULL, true, 'AW', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('8a720935-db68-43e2-b16d-34383ec6c3e8', 'Rony Chatterjee', 'tursio-1765825952645', 'fb748f2e-dec1-496c-9470-6be1c23b7dfd', NULL, '{}', '2025-12-15 19:12:32.691217+00', '2025-12-15 19:12:32.691217+00', NULL, NULL, 'rony', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'TUR', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('c3100bea-82a6-4365-b159-6581f1be9be3', 'Sebastian Henkel', 'as1', '51a05157-0aa7-42b5-a6e5-acf43d436a4b', NULL, '{"company_name": "Asphericon", "workspace_code": "AS1", "default_timezone": "Europe/Berlin", "default_country_code": "DE", "default_working_hours": {"end": 17, "start": 9}}', '2025-11-28 09:24:33.444261+00', '2025-11-28 09:24:33.444261+00', NULL, NULL, 'asphericon', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'AAS', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('aa1a214c-02f0-4f3a-8849-92c7a50ee4f7', 'Brian Neirby', 'cm1', 'd518b2c7-bf3c-4112-99c5-e6c76fe27615', NULL, '{"company_name": "ChillMine", "workspace_code": "CM1"}', '2025-11-28 09:35:00.637109+00', '2025-11-28 09:35:00.637109+00', NULL, NULL, 'brian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'CM1', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('7f0341da-88db-476b-ae0a-fc0da5b70861', 'Charissa Saniel', 'ia4', '744649a8-d015-4ff7-9e41-983cc9ca7b79', NULL, '{"default_timezone": "America/Los_Angeles", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 5}}', '2025-11-08 03:31:30.943649+00', '2025-12-12 13:40:02.866+00', NULL, NULL, 'charissa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'IA4', NULL, true);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('2a8f7c3d-9b1e-4f6a-8c2d-5e9a1b4f7d3c', 'Chona Lamberte', 'ia6', 'dbbddc37-8740-4614-b448-53e0bfff2290', NULL, '{"default_timezone": "America/Los_Angeles", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 5}}', '2025-11-08 03:31:30.943649+00', '2025-12-12 13:40:16.102+00', NULL, NULL, 'chona', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'IA6', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('96c03b38-a2f4-40de-9e16-43098599e1d4', 'Irish Maguad', 'ia3', '1949f7fc-f354-47ba-98f1-ae0a7d3b1d5d', NULL, '{"default_timezone": "America/Los_Angeles", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 5}}', '2025-11-08 03:31:30.943649+00', '2025-12-12 13:40:02.808+00', NULL, NULL, 'irish', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'IA3', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('cd57981a-e63b-401c-bde1-ac71752c2293', 'Jennifer Fleming', 'ia5', 'a4c3ff4d-ac9c-4e84-9b35-967ce6ff8189', NULL, '{"default_timezone": "America/Los_Angeles", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 5}}', '2025-11-08 03:31:30.943649+00', '2025-12-12 13:40:02.917+00', NULL, NULL, 'jennifer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'IA5', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('04666209-fce8-4d71-8eaf-01278edfc73b', 'Michelle Gestuveo', 'ia2', '471bcb15-cc53-44f3-b5d2-4b97bb7a8b2f', NULL, '{"default_timezone": "America/Los_Angeles", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 5}}', '2025-11-08 03:31:30.943649+00', '2025-12-12 13:40:02.663+00', NULL, NULL, 'michelle', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'IA2', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('dea5a7f2-673c-4429-972d-6ba5fca473fb', 'Samantha Truman', 'true-people-consulting-mggnoauz', '1d1004ef-3cc7-47b3-942d-58c86f0a27c2', NULL, '{"default_timezone": "America/New_York", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 8}}', '2025-10-07 14:29:11.508637+00', '2025-10-07 14:29:11.508637+00', NULL, NULL, 'samantha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'TPC', '3cubed', false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('5b81ee67-4d41-4997-b5a4-e1432e060d12', 'Stan Bounev', 'stan-bounev-fresh', '6a927440-ebe1-49b4-ae5e-fbee5d27944d', NULL, '{"default_timezone": "America/Los_Angeles", "default_country_code": "US", "default_working_hours": {"end": 17, "start": 8}}', '2025-12-10 18:57:48.512807+00', '2025-12-10 18:57:48.512807+00', NULL, NULL, 'stan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'SB', NULL, false);
INSERT INTO public.workspaces (id, name, slug, owner_id, organization_id, settings, created_at, updated_at, trial_ends_at, billing_starts_at, tenant, company_url, detected_industry, company_description, target_personas, pain_points, value_proposition, key_competitors, pricing_model, website_analysis_status, website_analyzed_at, manual_overrides, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_cancelled_at, subscription_cancel_at, is_active, client_code, reseller_affiliation, commenting_agent_enabled) VALUES ('babdcab8-1a78-4b2f-913e-6e9fd9821009', 'Thorsten Linz', 'ia1', 'f6885ff3-deef-4781-8721-93011c990b1b', '91768a00-35cf-4633-ae4c-092585dd67fb', '{"theme": "dark", "timezone": "America/New_York", "email_domain": "innovareai.com", "linkedin_limits": {"message_delay_max": 180, "message_delay_min": 30, "daily_connection_requests": 100, "daily_messages_per_account": 800}, "default_timezone": "America/Los_Angeles", "linkedin_rollout": {"version": "1.0.0", "enabled_date": "2025-09-23T10:31:12.124Z", "features_included": ["Unipile hosted authentication", "Multi-account messaging", "LinkedIn ID resolution", "Campaign integration", "MCP tools integration", "Rate limit protection", "Geographic proxy routing"]}, "linkedin_features": {"messaging": true, "rate_limiting": true, "prospect_research": true, "automated_sequences": true, "connection_requests": true, "campaign_integration": true, "multi_account_support": true}, "default_country_code": "US", "default_working_hours": {"end": 17, "start": 5}, "linkedin_integration_enabled": true}', '2025-09-01 00:00:00+00', '2025-12-12 13:40:02.511+00', NULL, NULL, 'thorsten', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL, '{}', NULL, NULL, 'active', NULL, NULL, true, 'IA1', 'innovareai', true);


--
-- PostgreSQL database dump complete
--

\unrestrict Nzlvjhq4pSIbcsUwQLU7uhyUMjMOzYxHjmacU1nqPx9CN83RxjH8iFskeh0lsZv

