#!/bin/bash

# Email Queue Cron Job Setup Script
# This script provides the configuration needed for cron-job.org

echo "======================================================================"
echo "EMAIL QUEUE CRON JOB CONFIGURATION"
echo "======================================================================"
echo ""
echo "Go to: https://cron-job.org/en/members/"
echo ""
echo "Click: 'Create cronjob'"
echo ""
echo "======================================================================"
echo "CONFIGURATION DETAILS"
echo "======================================================================"
echo ""
echo "Title:"
echo "  SAM Email Queue Processor"
echo ""
echo "URL:"
echo "  https://app.meet-sam.com/api/cron/process-email-queue"
echo ""
echo "Schedule:"
echo "  */13 * * * *"
echo "  (Translation: Every 13 minutes)"
echo ""
echo "Request Method:"
echo "  POST"
echo ""
echo "Request Timeout:"
echo "  60 seconds"
echo ""
echo "======================================================================"
echo "HEADERS (CRITICAL)"
echo "======================================================================"
echo ""
echo "Header Name: x-cron-secret"
echo "Header Value: 792e0c09eeee1a229b78a6341739613177fad24f401b1c82f2673bbb9ee806a0"
echo ""
echo "======================================================================"
echo "NOTIFICATIONS (Optional)"
echo "======================================================================"
echo ""
echo "Enable notifications for:"
echo "  - Execution failures"
echo "  - Disable notifications for successful runs (too noisy)"
echo ""
echo "======================================================================"
echo "TESTING THE ENDPOINT"
echo "======================================================================"
echo ""
echo "Testing endpoint now..."
echo ""

curl -X POST https://app.meet-sam.com/api/cron/process-email-queue \
  -H "x-cron-secret: 792e0c09eeee1a229b78a6341739613177fad24f401b1c82f2673bbb9ee806a0" \
  -H "Content-Type: application/json" \
  -s | jq '.'

echo ""
echo "======================================================================"
echo "EXPECTED RESPONSES"
echo "======================================================================"
echo ""
echo "If NO emails in queue:"
echo '  {"success": true, "message": "No emails ready to send", "processed": 0}'
echo ""
echo "If outside business hours (8 AM - 5 PM):"
echo '  {"success": true, "message": "Outside business hours...", "processed": 0}'
echo ""
echo "If email sent successfully:"
echo '  {"success": true, "message": "Email sent successfully", "processed": 1, ...}'
echo ""
echo "======================================================================"
echo "AFTER CONFIGURING CRON JOB"
echo "======================================================================"
echo ""
echo "1. Enable the cron job"
echo "2. Wait for first execution (check execution log)"
echo "3. Verify with: bash scripts/check-email-queue.sh"
echo ""
echo "======================================================================"
